### ISSUE TITLE
Measure distance driven of multiple walls

### ISSUE THREAD

**Issue by SusanLieu** [DIT112-V19/group-09#8]
## Description

As a home owner, I want the car to measure the distance of a wall in my home so that I can purchase furniture for that space accordingly.

## Acceptance Criteria

The car will be placed at a starting point of choice, 10cm from the wall.
The car will start when prompted by the android app.
The car will use its odometers in order to measure the distance driven up to a chosen wall to end measurement.
The car will automatically change direction once it's stopped and continue along the wall.
The car will output distance telemetrics to the android app after it's done running.

**Comment by gusmikaja** [comment]
## Acceptance Criteria

The car will be placed at a starting point of choice with a laptop connected.
The car will use its odometers in order to measure the distance driven up to a chosen wall to end measurement.
The car will automatically change direction once it's stopped and continue along the wall.
The car will be connected to the computer at all times when running the program.
The computer will be held by the user when the car is running.
The car will output distance telemetrics to the computer after it's done running.
